/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhodoleonardo;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author Breno
 */
public class Programa1 extends javax.swing.JFrame {

    /**
     * Creates new form Programa1
     */
    Node nodoRoot;
    Node atual = new Node();

    public void atualizaTextoDaCaixa(String texto) {
        this.jTextField1.setText(texto);
    }

    public Programa1() {
        initComponents();
        manipulaDados();
        nodoRoot = Node.getRoot();
        atual = nodoRoot;
        jTextField1.setText(nodoRoot.texto);
    }

    public void manipulaDados() {
        jButton1.setVisible(false);
        jButton2.setVisible(false);
        jLabel1.setVisible(false);
        jTextField1.setVisible(false);
    }

    public void desmanipulaDados() {
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jLabel1.setVisible(true);
        jTextField1.setVisible(true);
    }

    public void emCasoDeAcerto() {
        manipulaDados();
        jButton3.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Sim");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Nao");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Pergunta:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton3.setText("Inicio");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Pense em um animal.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(111, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Clicou SIM
        //VERIFICA SE O NODO ATUAL TEM DOIS FILHOS COM TEXTO, SE SIM PERCORRE COM BASE NA RESPOSTA E VAI PRA PROXIMA BRANCH
        //ELSE IF SE NAO TIVER FILHO DA ESQUERDA, VERIFICA
        //SEU CASO BASE EH: EH UMA RESPOSTA? JOGA SOBRE FORMA DE PERGUNTA, SE DER ERRADO TRATE A ARVORE E COMECE DENOVO
        //inicio do caso base
        if(atual.direita == null){
            System.out.println("Aqui caiu no caso bizarro, sei la o que aconteceu");
            String resposta = JOptionPane.showInputDialog(rootPane, "Informe agora o nome do seu animal");
            atual.direita = new Node(resposta, null, null);
            atual = nodoRoot;
            emCasoDeAcerto();
        }
        //Aqui caiu no caso do filho da direita ser uma resposta, ai manda-se sobre forma de pergunta
        else if(atual.verificaPergunta(atual.direita) == false){
            
            int reply = JOptionPane.showConfirmDialog(rootPane, "O seu animal eh o:"+ atual.direita.getTexto()+"?");
            
            if(reply == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(rootPane, "Acertei");
                atual = nodoRoot;
                emCasoDeAcerto();
            }
            
            else if(reply == JOptionPane.NO_OPTION){
                String pergunta = JOptionPane.showInputDialog(rootPane, "Escreva uma pergunta que diferencie o meu animal do seu:");
                String resposta = JOptionPane.showInputDialog(rootPane, "Informe agora o nome do seu animal");
                Node respostaCerta = new Node(pergunta, new Node(atual.direita.texto), new Node(resposta));
                atual.direita = respostaCerta;
                emCasoDeAcerto();
                atual = nodoRoot;
                //Reinicia o codigo com os botoes visiveis invisiveis e os que foram apagados voltam a ser vistos
                //reinicia o nodoAtual como root
            }
            else{
                //Caiu no Cancel, nao faz nada
            }
        }
        
        //Pergunta
        //Se cair aqui, o usuario clicou sim e tem uma pergunta, move o nodo atual para a direita e da display na pergunta
        else if(atual.verificaPergunta(atual.direita)){
            atual = atual.direita;
            atualizaTextoDaCaixa(atual.texto);
        }
        //fim do caso base  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        jLabel1.setVisible(true);
        jTextField1.setVisible(true);
        jButton3.setVisible(false);
        jLabel2.setVisible(false);
        atual = nodoRoot.root;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //comeca caso base 1
        if(atual.esquerda == null){
            String resposta = JOptionPane.showInputDialog(rootPane, "Informe agora o nome do seu animal");
            atual.esquerda = new Node(resposta, null, null);
            atual = nodoRoot;
            emCasoDeAcerto();
        }
        //No caso de baixo pega-se a resposta e lanca como pergunta
        else if(atual.verificaPergunta(atual.esquerda)==false){
            int reply2 = JOptionPane.showConfirmDialog(rootPane, "Por acaso o seu animal eh o:"+ atual.esquerda.getTexto() + "?");
            
            if(reply2 == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(rootPane, "Acertei");
                atual = nodoRoot;
                emCasoDeAcerto();
            }
            else if(reply2 == JOptionPane.NO_OPTION){
                String pergunta = JOptionPane.showInputDialog(rootPane, "Escreva uma pergunta que diferencie o meu animal do seu:");
                String resposta = JOptionPane.showInputDialog(rootPane, "Informe agora o nome do seu animal");
                Node esquerdo = new Node(pergunta, new Node(atual.esquerda.getTexto()), new Node(resposta));
                atual.esquerda = esquerdo;
                atual = nodoRoot;
                emCasoDeAcerto();
            }
            else{
                //Caiu no Cancel, nao faz nada
            }
        }
        
        //Nesse caso atualiza-se o atual e atualiza-se o JTextField
        else if(atual.verificaPergunta(atual.esquerda)){
            atual = atual.esquerda;
            atualizaTextoDaCaixa(atual.getTexto());
        }
        //fim do caso base
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Programa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Programa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Programa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Programa1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Programa1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
